<a href="https://colab.research.google.com/github/RobertBWeidlich/Colab_Notebooks/blob/main/CnNB_002_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# CnNB 002 Numpy
# Python Machine Learning, Wei-Meng Lee, chapter 2                                                                                          

In [1]:
import numpy as np

In [3]:
a1 = np.arange(10)
print(type(a1))
a1

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a7 = np.random.random((3,5))
a7

array([[0.5267125 , 0.47314155, 0.16738442, 0.80001981, 0.68494081],
       [0.39656028, 0.3938665 , 0.1946456 , 0.10258036, 0.80880103],
       [0.54126088, 0.76766747, 0.95784348, 0.92369953, 0.10543973]])

In [8]:
# create numpy array from raw data
# https://numpy.org/doc/stable/user/basics.creation.html
a51 = np.array(([1,2,3], [4,5,6], [7,8,9]))
print(type(a51))
a51

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a52 = np.array(([1,2,3], [4,5,6], [7,8,9]), ([1,2,3], [4,5,6], [7,8,9]))
print(type(a52))
a52

TypeError: ignored